#!/bin/bash
# docker build \
#        --platform=
#        -f $DOCKERFILE_PATH -t $IMAGE_NAME .
echo uname -a
uname -a

echo docker info
docker info

echo docker buildx inspect --bootstrap
docker buildx inspect --bootstrap

echo docker buildx ls
docker buildx ls

echo docker run --rm --privileged multiarch/qemu-user-static:register
docker run --rm --privileged multiarch/qemu-user-static:register

echo mount
mount

for f in /proc/sys/fs/binfmt_misc/*
do
    echo cat $f
    cat $f
done

docker run --rm alpine@a220fbceafab4a9af7dd7b574eea7ce646dc5ab57d0b7fcd1f349dcca3d66929 ls

echo docker buildx create --driver docker-container --use
docker buildx create --driver docker-container --use

echo End build hook
