name: build-stage3

on:
  push:
    tags:
      - 'stage3-*'

env:
  ORG: andzuc
    
jobs:
  setup-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
  build:
    runs-on: ubuntu-latest
    needs: setup-buildx
    strategy:
      matrix:
        target:
          # - portage
          - stage3-amd64
          # - stage3-amd64-hardened
          # - stage3-amd64-hardened-nomultilib
          # - stage3-amd64-musl-hardened
          # - stage3-amd64-musl-vanilla
          # - stage3-amd64-nomultilib
          # - stage3-amd64-systemd
          # - stage3-amd64-uclibc-hardened
          # - stage3-amd64-uclibc-vanilla
          # - stage3-arm64
          # - stage3-arm64-systemd
          # - stage3-armv5tel
          # - stage3-armv6j_hardfp
          - stage3-armv7a_hardfp
          # - stage3-ppc64le
          # - stage3-s390x
          - stage3-x86
          # - stage3-x86-hardened
          # - stage3-x86-musl-vanilla
          # - stage3-x86-systemd
          # - stage3-x86-uclibc-hardened
          # - stage3-x86-uclibc-vanilla
    steps:
      - name: Build image
        env:
          TARGET: ${{matrix.target}}
        run: |
          echo "Building TARGET: ${ORG}/${TARGET}"
          ./build.sh
      - name: Inspect image
        run: docker image inspect "${ORG}/${TARGET/-/:}"
